name: CI

on:
  push:
    branches-ignore:
      - 'main'

env:
  PACKAGE_NAME: smithy-iot-device-sdk-greengrass-ipc

jobs:
  linux-compat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - manylinux2014-x64
          - al2-x64
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Build ${{ env.PACKAGE_NAME }}
        run: ./gradlew build

  linux-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Build ${{ env.PACKAGE_NAME }}
        run: ./gradlew build